export const HEADER = {
    CHANGE_TITLE: 'CHANGE_HEADER_TITLE'
}

export const MESSAGE_LIST = {
    PUSH: 'PUSH_MESSAGE_LIST',
    CLEAR: 'CLEAR_MESSAGE_LIST'
}

export const REGISTER = {
    CHANGE_ROOM: 'CHANGE_REGISTER_ROOM',
    SAVE_ROOM: 'SAVE_ROOM',
    CHANGE_NICKNAME: 'CHANGE_REGISTER_NICKNAME',
    SAVE_NICKNAME: 'SAVE_NICKNAME'
}

export const USERINPUT = {
    CHANGE: 'ONCHANG_USER_INPUT',
    SEND: 'SEND_USER_INPUT',
    CLEAR: 'CLEAR_USER_INPUT'
}

export const ONLINELIST = {
    FRESH: 'ONLINELIST_FRESH'
}